name: loggable
description: Dart Loggable mixin.
version: 1.0.1
homepage: https://github.com/Hacker-CB/dart-loggable.git
author: Pavel Sokolov <pavel@sokolov.me>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  logging: ^0.11.3+2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
